# Generated by Django 5.2.4 on 2025-07-27 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lia.intelligentlink",
                    ),
                ),
            ],
        ),
    ]
