# Generated by Django 5.2.4 on 2025-07-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_of_birth_user_id_card_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id_card_path",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_path",
        ),
        migrations.RemoveField(
            model_name="user",
            name="selfie_path",
        ),
        migrations.RemoveField(
            model_name="user",
            name="selfie_with_id_path",
        ),
        migrations.AddField(
            model_name="user",
            name="id_card",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="selfie",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="user",
            name="selfie_with_id",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
    ]
